[tool.black]
adopts = '--fast' #may yield briken ast, but much faster
exclude = '''
(
    /(
        \.git
      | \.venv
      | django_project/telegrambot/common/migrations
      | django_project/telegrambot/usersmanage/migrations
    )/
)
'''
line-length = 120
target_version = ['py38']

[tool.isort]
known_third_party = ['django', 'rest_framework_extensions', 'aiogram']
known_first_party = ["common", "usersmanage",]
line_length = 120
skip="migrations, templates,__init__.py,"
skip_gitignore = "True"
force_single_line = "True"
lines_after_imports = 2